### PR TITLE
- added option to use the bounding box as chunk size for MagicaVox *.…

### PR DESCRIPTION
**Pull request by simlu**
…vox exporter

### CODE REVIEW

**Comment by funabab** [comment]
Looks nice... Will test, but i think the bounding box option should be renamed to "fit to size" (what i did but i haven't tested it much so no PR). There is also an option in MV that does that so it will self explanatory for MV users

**Comment by simlu** [comment]
Ah, basically the inverted option! Makes sense and I'll change it later.

**Comment by funabab** [comment]
Yeah, inverted option... Should be very easy to do.

**Comment by simlu** [comment]
Done. Please review and approve if ok! @funabab

**Comment by funabab** [comment]
All good to go, nice job 👍

**Comment by simlu** [comment]
You still need to approve!

**Comment by simlu** [comment]
Re-did changes in different branch...

**Pull request closed without merging**
