### PR TITLE
Improve Chinese translation, and updated some help text strings

### PR DESCRIPTION
**Pull request by maijz128**

### CODE REVIEW

**Comment by simlu** [comment]
Merged. Will go out with next release. Probably next weekend unless you need it for some reason?

**Comment by maijz128** [comment]
No problem!  I look forward to more features.

**Comment by simlu** [comment]
Sweet!

Feel free to comment on the github issues that you think are important or even open a new one!

**Comment by maijz128** [comment]
Yes, I will.

**Pull request merged**
