### PR TITLE
Improve Chinese translation，and make help frame display utf-8 text

### PR DESCRIPTION
**Pull request by maijz128**

### CODE REVIEW

**Comment by simlu** [comment]
That won't work unfortunately.

Can you try to replace `resource/font/font.ttf` with a Chinese font instead? That should work properly and we can then include that font in the bundle.

**Comment by maijz128** [comment]
Not work? 😂
Yes, I can replace font, it is work. but the Chinese font a little big. (10MB)

**Comment by simlu** [comment]
Which font did you have in mind? I tried a few but they didn't work...

**Comment by maijz128** [comment]
I am using this font -> [SimSun](https://www.fontpalace.com/font-download/SimSun/).
Are you testing Chinese? Or test English?
This code is work in my Chinese environment.

**Comment by maijz128** [comment]
Does this code make it impossible to run?
if yes, Then give up this code.

**Comment by maijz128** [comment]
My English is not so good . please forgive me.

**Comment by maijz128** [comment]
Yes, You fixed it. It works.

**Pull request closed without merging**
